"""phase five voice and agents

Revision ID: 0b70e7cda204
Revises: 5974eb053128
Create Date: 2026-06-20 20:46:56.373749

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b70e7cda204'
down_revision = '5974eb053128'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_interactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('community_id', sa.Integer(), nullable=True),
    sa.Column('agent_type', sa.String(length=50), nullable=False),
    sa.Column('channel', sa.String(length=30), nullable=False),
    sa.Column('transcript', sa.Text(), nullable=False),
    sa.Column('outcome', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("channel IN ('browser_voice', 'phone_call', 'text', 'system')", name='ck_agent_interactions_channel'),
    sa.ForeignKeyConstraint(['community_id'], ['communities.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('agent_interactions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agent_interactions_community_id'), ['community_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_interactions_user_id'), ['user_id'], unique=False)

    op.create_table('voice_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('agent_type', sa.String(length=30), nullable=False),
    sa.Column('mode', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('language_hint', sa.String(length=20), nullable=True),
    sa.Column('external_id', sa.String(length=100), nullable=True),
    sa.Column('transcript', sa.Text(), nullable=False),
    sa.Column('outcome', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("agent_type IN ('onboarding', 'hotline', 'task_followup')", name='ck_voice_sessions_agent_type'),
    sa.CheckConstraint("mode IN ('browser', 'twilio')", name='ck_voice_sessions_mode'),
    sa.CheckConstraint("status IN ('active', 'completed', 'failed')", name='ck_voice_sessions_status'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('voice_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_voice_sessions_external_id'), ['external_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_voice_sessions_user_id'), ['user_id'], unique=False)

    op.create_table('agent_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('agent_type', sa.String(length=50), nullable=False),
    sa.Column('community_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('event_plan_id', sa.Integer(), nullable=True),
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('input_json', sa.JSON(), nullable=False),
    sa.Column('output_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('started', 'completed', 'failed')", name='ck_agent_runs_status'),
    sa.ForeignKeyConstraint(['community_id'], ['communities.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['event_plan_id'], ['event_plans.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('agent_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agent_runs_agent_type'), ['agent_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_runs_community_id'), ['community_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_runs_event_plan_id'), ['event_plan_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_runs_task_id'), ['task_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_runs_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agent_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agent_runs_user_id'))
        batch_op.drop_index(batch_op.f('ix_agent_runs_task_id'))
        batch_op.drop_index(batch_op.f('ix_agent_runs_event_plan_id'))
        batch_op.drop_index(batch_op.f('ix_agent_runs_community_id'))
        batch_op.drop_index(batch_op.f('ix_agent_runs_agent_type'))

    op.drop_table('agent_runs')
    with op.batch_alter_table('voice_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_voice_sessions_user_id'))
        batch_op.drop_index(batch_op.f('ix_voice_sessions_external_id'))

    op.drop_table('voice_sessions')
    with op.batch_alter_table('agent_interactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agent_interactions_user_id'))
        batch_op.drop_index(batch_op.f('ix_agent_interactions_community_id'))

    op.drop_table('agent_interactions')
    # ### end Alembic commands ###
