"""phase one core models

Revision ID: 2495e9041bb3
Revises: 
Create Date: 2026-06-20 20:12:39.812748

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2495e9041bb3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('communities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nationality', sa.String(length=120), nullable=False),
    sa.Column('location', sa.String(length=160), nullable=False),
    sa.Column('display_name', sa.String(length=300), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nationality', 'location', name='uq_communities_nationality_location')
    )
    with op.batch_alter_table('communities', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_communities_location'), ['location'], unique=False)
        batch_op.create_index(batch_op.f('ix_communities_nationality'), ['nationality'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('phone_number', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('preferred_language', sa.String(length=80), nullable=True),
    sa.Column('location', sa.String(length=160), nullable=True),
    sa.Column('primary_nationality', sa.String(length=120), nullable=True),
    sa.Column('secondary_interest', sa.String(length=120), nullable=True),
    sa.Column('onboarding_status', sa.String(length=20), nullable=False),
    sa.Column('task_failure_count', sa.Integer(), nullable=False),
    sa.Column('restricted_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("onboarding_status IN ('started', 'completed')", name='ck_users_onboarding_status'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_location'), ['location'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_primary_nationality'), ['primary_nationality'], unique=False)

    op.create_table('community_memberships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('community_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("role IN ('member', 'organizer', 'steward', 'admin')", name='ck_memberships_role'),
    sa.CheckConstraint("status IN ('active', 'inactive')", name='ck_memberships_status'),
    sa.ForeignKeyConstraint(['community_id'], ['communities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'community_id', name='uq_memberships_user_community')
    )
    with op.batch_alter_table('community_memberships', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_community_memberships_community_id'), ['community_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_community_memberships_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('community_memberships', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_community_memberships_user_id'))
        batch_op.drop_index(batch_op.f('ix_community_memberships_community_id'))

    op.drop_table('community_memberships')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_primary_nationality'))
        batch_op.drop_index(batch_op.f('ix_users_location'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('communities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_communities_nationality'))
        batch_op.drop_index(batch_op.f('ix_communities_location'))

    op.drop_table('communities')
    # ### end Alembic commands ###
