"""phase three event planning

Revision ID: 39a87dd6059f
Revises: bbd0c58f7194
Create Date: 2026-06-20 20:27:43.023636

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39a87dd6059f'
down_revision = 'bbd0c58f7194'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('budget_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_plan_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=30), nullable=False),
    sa.Column('description', sa.String(length=300), nullable=False),
    sa.Column('estimated_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('actual_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("category IN ('venue', 'food', 'decor', 'supplies', 'transport', 'entertainment', 'other')", name='ck_budget_items_category'),
    sa.CheckConstraint("status IN ('estimated', 'approved', 'spent')", name='ck_budget_items_status'),
    sa.ForeignKeyConstraint(['event_plan_id'], ['event_plans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('budget_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_budget_items_event_plan_id'), ['event_plan_id'], unique=False)

    op.create_table('events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_plan_id', sa.Integer(), nullable=False),
    sa.Column('community_id', sa.Integer(), nullable=False),
    sa.Column('organizer_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('event_type', sa.String(length=80), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('venue_name', sa.String(length=200), nullable=True),
    sa.Column('venue_address', sa.String(length=300), nullable=True),
    sa.Column('budget_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('published', 'completed', 'cancelled')", name='ck_events_status'),
    sa.ForeignKeyConstraint(['community_id'], ['communities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['event_plan_id'], ['event_plans.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organizer_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_plan_id')
    )
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_events_community_id'), ['community_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_events_organizer_id'), ['organizer_id'], unique=False)

    op.create_table('venue_candidates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_plan_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('address', sa.String(length=300), nullable=False),
    sa.Column('phone_number', sa.String(length=32), nullable=True),
    sa.Column('website_url', sa.String(length=500), nullable=True),
    sa.Column('maps_url', sa.String(length=500), nullable=True),
    sa.Column('rating', sa.Numeric(precision=2, scale=1), nullable=True),
    sa.Column('review_count', sa.Integer(), nullable=True),
    sa.Column('estimated_cost', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('capacity', sa.Integer(), nullable=True),
    sa.Column('accessibility_notes', sa.Text(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('source', sa.String(length=30), nullable=False),
    sa.Column('source_place_id', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("source IN ('google_places', 'mock', 'manual')", name='ck_venues_source'),
    sa.CheckConstraint("status IN ('suggested', 'selected', 'rejected')", name='ck_venues_status'),
    sa.ForeignKeyConstraint(['event_plan_id'], ['event_plans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_plan_id', 'source_place_id', name='uq_venues_plan_source_place')
    )
    with op.batch_alter_table('venue_candidates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_venue_candidates_event_plan_id'), ['event_plan_id'], unique=False)

    op.create_table('tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_plan_id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=30), nullable=False),
    sa.Column('assignee_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('estimated_cost', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('created_by_agent', sa.Boolean(), nullable=False),
    sa.Column('self_reported_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("category IN ('food', 'decor', 'venue', 'setup', 'cleanup', 'outreach', 'supplies', 'transport', 'other')", name='ck_tasks_category'),
    sa.CheckConstraint("priority IN ('low', 'medium', 'high')", name='ck_tasks_priority'),
    sa.CheckConstraint("status IN ('draft', 'open', 'claimed', 'done', 'failed', 'cancelled')", name='ck_tasks_status'),
    sa.ForeignKeyConstraint(['assignee_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['event_plan_id'], ['event_plans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tasks_assignee_id'), ['assignee_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tasks_event_id'), ['event_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tasks_event_plan_id'), ['event_plan_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tasks_event_plan_id'))
        batch_op.drop_index(batch_op.f('ix_tasks_event_id'))
        batch_op.drop_index(batch_op.f('ix_tasks_assignee_id'))

    op.drop_table('tasks')
    with op.batch_alter_table('venue_candidates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_venue_candidates_event_plan_id'))

    op.drop_table('venue_candidates')
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_events_organizer_id'))
        batch_op.drop_index(batch_op.f('ix_events_community_id'))

    op.drop_table('events')
    with op.batch_alter_table('budget_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_budget_items_event_plan_id'))

    op.drop_table('budget_items')
    # ### end Alembic commands ###
