"""phase four community execution

Revision ID: 5974eb053128
Revises: 39a87dd6059f
Create Date: 2026-06-20 20:35:52.473552

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5974eb053128'
down_revision = '39a87dd6059f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attendance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('checked_in_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('attended', 'no_show')", name='ck_attendance_status'),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id', 'user_id', name='uq_attendance_event_user')
    )
    with op.batch_alter_table('attendance', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_attendance_event_id'), ['event_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_attendance_user_id'), ['user_id'], unique=False)

    op.create_table('rsvps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('yes', 'no', 'maybe')", name='ck_rsvps_status'),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id', 'user_id', name='uq_rsvps_event_user')
    )
    with op.batch_alter_table('rsvps', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rsvps_event_id'), ['event_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_rsvps_user_id'), ['user_id'], unique=False)

    op.create_table('task_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('reporter_id', sa.Integer(), nullable=False),
    sa.Column('report_text', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('submitted', 'accepted', 'needs_followup', 'rejected')", name='ck_task_reports_status'),
    sa.ForeignKeyConstraint(['reporter_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('task_reports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_task_reports_reporter_id'), ['reporter_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_task_reports_task_id'), ['task_id'], unique=False)

    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('attendance_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('completion_notes', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_column('completed_at')
        batch_op.drop_column('completion_notes')
        batch_op.drop_column('attendance_count')

    with op.batch_alter_table('task_reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_task_reports_task_id'))
        batch_op.drop_index(batch_op.f('ix_task_reports_reporter_id'))

    op.drop_table('task_reports')
    with op.batch_alter_table('rsvps', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rsvps_user_id'))
        batch_op.drop_index(batch_op.f('ix_rsvps_event_id'))

    op.drop_table('rsvps')
    with op.batch_alter_table('attendance', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_attendance_user_id'))
        batch_op.drop_index(batch_op.f('ix_attendance_event_id'))

    op.drop_table('attendance')
    # ### end Alembic commands ###
