"""phase two cultural scanner and suggestions

Revision ID: bbd0c58f7194
Revises: 2495e9041bb3
Create Date: 2026-06-20 20:21:04.234438

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bbd0c58f7194'
down_revision = '2495e9041bb3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cultural_moments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nationality', sa.String(length=120), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('type', sa.String(length=30), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('day', sa.Integer(), nullable=False),
    sa.Column('is_recurring', sa.Boolean(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('suggested_event_types_json', sa.JSON(), nullable=False),
    sa.Column('planning_lead_days', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("type IN ('national_holiday', 'religious', 'food', 'tradition', 'seasonal', 'community')", name='ck_cultural_moments_type'),
    sa.CheckConstraint('day BETWEEN 1 AND 31', name='ck_cultural_moments_day'),
    sa.CheckConstraint('month BETWEEN 1 AND 12', name='ck_cultural_moments_month'),
    sa.CheckConstraint('planning_lead_days >= 0', name='ck_cultural_moments_lead_days'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nationality', 'title', 'month', 'day', name='uq_cultural_moments_identity')
    )
    with op.batch_alter_table('cultural_moments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cultural_moments_nationality'), ['nationality'], unique=False)

    op.create_table('event_suggestions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('community_id', sa.Integer(), nullable=False),
    sa.Column('suggested_for_user_id', sa.Integer(), nullable=True),
    sa.Column('source_type', sa.String(length=40), nullable=False),
    sa.Column('source_ref_id', sa.Integer(), nullable=True),
    sa.Column('source_key', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_by_agent', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("source_type IN ('cultural_calendar', 'new_member', 'user_request', 'low_activity', 'successful_past_event')", name='ck_event_suggestions_source_type'),
    sa.CheckConstraint("status IN ('pending', 'accepted', 'dismissed', 'expired')", name='ck_event_suggestions_status'),
    sa.ForeignKeyConstraint(['community_id'], ['communities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['suggested_for_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('event_suggestions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_event_suggestions_community_id'), ['community_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_event_suggestions_source_key'), ['source_key'], unique=True)
        batch_op.create_index(batch_op.f('ix_event_suggestions_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_event_suggestions_suggested_for_user_id'), ['suggested_for_user_id'], unique=False)

    op.create_table('event_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('suggestion_id', sa.Integer(), nullable=True),
    sa.Column('community_id', sa.Integer(), nullable=False),
    sa.Column('organizer_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('event_type', sa.String(length=80), nullable=True),
    sa.Column('target_date', sa.Date(), nullable=True),
    sa.Column('expected_attendees', sa.Integer(), nullable=True),
    sa.Column('budget_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('budget_currency', sa.String(length=3), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('draft', 'needs_review', 'approved', 'published', 'cancelled')", name='ck_event_plans_status'),
    sa.ForeignKeyConstraint(['community_id'], ['communities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organizer_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['suggestion_id'], ['event_suggestions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('suggestion_id')
    )
    with op.batch_alter_table('event_plans', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_event_plans_community_id'), ['community_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_event_plans_organizer_id'), ['organizer_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event_plans', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_event_plans_organizer_id'))
        batch_op.drop_index(batch_op.f('ix_event_plans_community_id'))

    op.drop_table('event_plans')
    with op.batch_alter_table('event_suggestions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_event_suggestions_suggested_for_user_id'))
        batch_op.drop_index(batch_op.f('ix_event_suggestions_status'))
        batch_op.drop_index(batch_op.f('ix_event_suggestions_source_key'))
        batch_op.drop_index(batch_op.f('ix_event_suggestions_community_id'))

    op.drop_table('event_suggestions')
    with op.batch_alter_table('cultural_moments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cultural_moments_nationality'))

    op.drop_table('cultural_moments')
    # ### end Alembic commands ###
